### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by comminman23** [tolgahanuzun/Flask-Login-Example#3]
getfollowedby(url):
    """View Instagram user follower count"""
    link = f'https://www.instagram.com/{https://instagram.com/sarahpearce13?igshid=YmMyMTA2M2Y=}/?__a=1'
    Sarahpearce13= requests.get(link)
    return (sarahpearce13.json()['graphql']['sarahpearce13']['edge_followed_by']['count'])

defSarahpearce13(url):
    """Split the URL from the username"""
    return url.split("instagram.com/")[1].replace("/", "")

**Comment by imvickykumar999** [comment]
> getfollowedby(url): """View Instagram user follower count""" link = f'[https://www.instagram.com/{https://instagram.com/sarahpearce13?igshid=YmMyMTA2M2Y=}/?__a=1](https://www.instagram.com/%7Bhttps://instagram.com/sarahpearce13?igshid=YmMyMTA2M2Y=%7D/?__a=1)' Sarahpearce13= requests.get(link) return (sarahpearce13.json()['graphql']['sarahpearce13']['edge_followed_by']['count'])
> 
> defSarahpearce13(url): """Split the URL from the username""" return url.split("instagram.com/")[1].replace("/", "")

`Try this...`
https://www.instagram.com/sarahpearce13/?__a=1&__d=1

**Comment by tolgahanuzun** [comment]
The API url has changed. I change and fix it. Thank you for the message. @imvickykumar999 @comminman23
